language: java


stages:
  - test
  - deploy

jobs:
  include:
    - name: test-mvn-jdk8
      jdk: openjdk8
      script: mvn clean test
    - name: test-mvn-jdk11
      jdk: openjdk11
      script: mvn clean test
    - name: test-ant-jdk8
      jdk: openjdk8
      before_install: 
        - sudo apt-get update
        - sudo apt-get install ant-optional
      script:
        - ant -f ant-build-script.xml test
    - name: test-ant-jdk11
      jdk: openjdk11
      before_install: 
        - sudo apt-get update
        - sudo apt-get install ant-optional
      script:
        - ant -f ant-build-script.xml test
    - name: test-schematron
      jdk: openjdk11
      script:
        - java -jar validation/lib/saxon9he.jar -o:schematron_rules_pd.md validation/rules/sbgn_pd.sch validation/schematron_to_markdown.xsl
        - java -jar validation/lib/saxon9he.jar -o:schematron_rules_af.md validation/rules/sbgn_af.sch validation/schematron_to_markdown.xsl
        - java -jar validation/lib/saxon9he.jar -o:schematron_rules_er.md validation/rules/sbgn_er.sch validation/schematron_to_markdown.xsl
        - cat schematron_rules_pd.md
        - cat schematron_rules_af.md
        - cat schematron_rules_er.md
    - stage: deploy
      name: deploy-wiki
      if: branch = master
      script:
        - cd ..
        - git clone "https://${GITHUB_TOKEN}@github.com/sbgn/sbgn.wiki.git"
        - mv -f libsbgn/*.md sbgn.wiki/
        - cd sbgn.wiki
        - git add schematron_rules_*.md 
        - git commit -m "Generated Wiki via Travis-CI"
        - git push
install: true
